version: '3.1'

services:

  mysqldb-inventory-service:
    image: "mysql"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: inventory-service
      MYSQL_USER: inventory-service
      MYSQL_PASSWORD: inventory-service123
      MYSQL_ROOT_PASSWORD: inventory-service123

  mysqldb-order-service:
    image: "mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: order-service
      MYSQL_USER: order-service
      MYSQL_PASSWORD: order-service123
      MYSQL_ROOT_PASSWORD: order-service123%

  mongo-product-service:
    image: mongo
    container_name: mongo-product-service
    restart: always
    ports:
      - "27017:27017"