spring:
  application:
    name: order-server
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: order-service
    password: order-service123
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

endpoints:
  http-rest:
    inventory: http://inventory-server/api/inventory

server:
  port: 8082
#  port: 0 # random port on startup