spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: order-service
    password: order-service123
  sql:
    init:
      mode: always

server:
  port: 8081