spring:
  application:
    name: inventory-server
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/inventory-service
    username: inventory-service
    password: inventory-service123
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
#  port: 8081
  port: 0 # random port on startup
