spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/inventory-service
    username: inventory-service
    password: inventory-service123
  sql:
    init:
      mode: always

server:
  port: 8082